default_stages: [commit]

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer

- repo: https://github.com/myint/autoflake
  rev: v2.3.1
  hooks:
  - id: autoflake
    args: [--in-place, --remove-unused-variables, --remove-all-unused-imports, --expand-star-imports]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.1
  hooks:
  - id: mypy

- repo: local
  hooks:
  - id: pytest-unit-tests
    name: pytest unit tests
    entry: pytest
    args: [tests/]
    language: python
    types: [python]
    stages: [push]
    pass_filenames: false
  - id: pytest-integration-tests
    name: pytest integration tests
    entry: pytest
    args: [integrationtests/]
    language: python
    types: [python]
    stages: [push]
    pass_filenames: false
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    types: [python]
    args: [--rcfile=pylintrc]

- repo: https://github.com/psf/black
  rev: 24.8.0
  hooks:
  - id: black
    args: [-l, '118']

- repo: https://github.com/commitizen-tools/commitizen
  rev: v3.28.0
  hooks:
  - id: commitizen
    stages: [commit-msg]

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-toml
    exclude: poetry.lock
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix]

- repo: meta
  hooks:
  - id: check-useless-excludes

- repo: https://github.com/hadolint/hadolint
  rev: v2.13.0-beta
  hooks:
  - id: hadolint-docker
    args: [-t, warning]

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.41.0
  hooks:
  - id: markdownlint-fix
    exclude: CHANGELOG.md

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v4.0.0-alpha.8
  hooks:
  - id: prettier
    types_or: [css, javascript, json]

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
    name: isort (python)
    args: [--profile, black]

- repo: https://github.com/renovatebot/pre-commit-hooks
  rev: 38.23.2
  hooks:
  - id: renovate-config-validator
