name: pytest

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
    - '**'

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332   # v4
      with:
        fetch-depth: 0
    - uses: mamba-org/setup-micromamba@4b9113af4fba0e9e1124b252dd6497a419e7396d # v1
      with:
        micromamba-version: 1.5.8-0
        environment-file: env.yml
        init-shell: >-
          bash
        cache-environment: true
    - name: Setup poetry
      run: |
        poetry config virtualenvs.create false
        poetry install
        poetry build
      shell: micromamba-shell {0}
    - name: Run tests
      run: ./test.sh
      shell: micromamba-shell {0}
