name: pytest

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
    - '**'

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      with:
        fetch-depth: 0
    - uses: mamba-org/setup-micromamba@0dea6379afdaffa5d528b3d1dabc45da37f443fc # v2
      with:
        micromamba-version: 1.5.8-0
        environment-file: env.yml
        init-shell: >-
          bash
        cache-environment: true
    - name: Setup poetry
      run: |
        poetry config virtualenvs.create false
        poetry install
        poetry build
      shell: micromamba-shell {0}
    - name: Run tests
      run: ./test.sh
      shell: micromamba-shell {0}
