name: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
    - main
    - dev
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      with:
        fetch-depth: 0
    - name: Cache compilation results
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
      env:
        cache-name: cache-nuitka
      with:
        path: ~/nuitka-cache
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - uses: mamba-org/setup-micromamba@0dea6379afdaffa5d528b3d1dabc45da37f443fc # v2
      with:
        micromamba-version: 1.5.8-0
        environment-file: env.yml
        init-shell: >-
          bash
        cache-environment: true
    - name: Setup poetry
      run: |
        poetry config virtualenvs.create false
      shell: micromamba-shell {0}
    - name: Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NUITKA_CACHE_DIR: ~/nuitka-cache
      run: |
        mkdir ~/nuitka-cache
        npx --package @semantic-release/git --package @semantic-release/changelog --package conventional-changelog-conventionalcommits --package semantic-release-replace-plugin  --package @semantic-release/exec semantic-release
      shell: micromamba-shell {0}
