name: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
    - main
    - dev
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: 0
    - name: Cache compilation results
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
      env:
        cache-name: cache-nuitka
      with:
        path: ~/nuitka-cache
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - uses: mamba-org/setup-micromamba@f8b8a1e23a26f60a44c853292711bacfd3eac822 # v1
      with:
        micromamba-version: 1.5.8-0
        environment-file: env.yml
        init-shell: >-
          bash
        cache-environment: true
    - name: Setup poetry
      run: |
        poetry config virtualenvs.create false
      shell: micromamba-shell {0}
    - name: Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NUITKA_CACHE_DIR: ~/nuitka-cache
      run: |
        mkdir ~/nuitka-cache
        npx --package @semantic-release/git --package @semantic-release/changelog --package conventional-changelog-conventionalcommits --package semantic-release-replace-plugin  --package @semantic-release/exec semantic-release
      shell: micromamba-shell {0}
